### ISSUE TITLE
Various issues with 1.9.2.2 to 2.0 migration

### ISSUE THREAD

**Issue by rkhoury82** [magento/data-migration-tool-ce#16]
Hi All,
I am having some difficulty migrating my pretty standard 1.9.2.2 shop;

Issues:

The migration completes but throws some warnings, per the logs below.

 - Getting two empty fields on the customer account (possible custom customer attributes from 1.9.2.2 store, that should have been ignored

- One of my attributes (size) on configurable products is asking to be selected prior to saving, this is only to be used for generating the simple product. 
(The value of attribute "size_config" must be set)

- That same attribute won't hold any changes when saved - for example, to show in column or to be filtered, change the setting from yes to no press save, it reverts back to yes.

- Price for configurable products is missing;

- cart sub total doesn't appear

- in Safari it won't go to the guest checkout page, asks to "create an account" but in Chrome works fine.

- Some products are showing a "special price" which is the amount less the tax - but others are fine.

I think all relate to the below warnings during migration? 

Errors:

An error that I was surprised to get was customer_entity.telephone was missing from source.
I set an ignore in the map-customer.xml.dist but the downside is the telephone number on the customer account isn't migrated. 

Steps taken:

Reindexed the 1.9.2.2 store and cleaned the cache
I ran the database repair tool against a reference database to ensure consistency.

Logs:

[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: catalog_category_product
[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: catalog_product_entity
[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: catalog_product_entity_datetime
[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: catalog_product_entity_decimal
[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: catalog_product_entity_int
[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: catalog_product_entity_media_gallery
[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: catalog_product_entity_media_gallery_value
[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: catalog_product_entity_text
[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: catalog_product_entity_varchar
[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: catalog_product_relation
[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: catalog_product_super_attribute
[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: catalog_product_super_attribute_label
[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: catalog_product_super_link
[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: catalog_product_website
[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: cataloginventory_stock_item
[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: cataloginventory_stock_status
[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: report_event
[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: report_viewed_product_index
[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: sales_bestsellers_aggregated_daily
[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: sales_bestsellers_aggregated_monthly
[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: sales_bestsellers_aggregated_yearly
[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: quote
[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: quote_address
[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: quote_item
[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: quote_item_option
[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: quote_payment
[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: sales_invoiced_aggregated
[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: sales_invoiced_aggregated_order
[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: sales_order_aggregated_created
[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: sales_order_aggregated_updated
[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: sales_shipping_aggregated
[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: sales_shipping_aggregated_order
[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: tax_order_aggregated_created
[2015-12-06 08:38:49][WARNING]: Mismatch of entities in the document: tax_order_aggregated_updated

Any help would be appreciated !

**Comment by Vincenkt** [comment]
Hi rkhoury82,

Please add tables name to <ignore> tag in map file. Your issue will be solved.

**Comment by rkhoury82** [comment]
Thanks for your suggestion;
These errors don't stop the migration, it works, it just throws a warning. If you have a look at those fields they are critical components of the migration. 
I suspect that mismatch is the reason for the corrupt data post migration.

**Comment by ilol** [comment]
@rkhoury82 do you want to close the issue?

**Comment by rkhoury82** [comment]
My various issues were solved by:
1 - Removing all non standard fields and tables prior to migration. (and not excluding via MAP.xml.dist)
2- I didnt realise that ALL of core_config_data is migrated - some of the custom modules settings were conflicting with Magento2.
The tool works as described.

**Comment by tejashp77** [comment]
[2018-01-12 16:43:13][ERROR]: Mismatch of entities in the document: catalog_product_entity_decimal

issue still coming. in which file we have to map and in which tag?

**Comment by Corsten** [comment]
@tejashp77 Have you solved the problem? 
i have the same issue. I migrate from 1.9.2.2 to 2.2.2.
